# Generated by Django 4.2.6 on 2023-10-29 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_member_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='residing_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='residing_country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='residing_state',
            new_name='state',
        ),
    ]
