# Generated by Django 4.2.6 on 2023-10-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_residing_city_member_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
